server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: sky-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: ${hongs.datasource.driver-class-name}
    url: jdbc:mysql://${hongs.datasource.host}:${hongs.datasource.port}/${hongs.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${hongs.datasource.username}
    password: ${hongs.datasource.password}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

springdoc:
  api-docs:
    enabled: true
  packages-to-scan: com.hongs.skyserver.controller

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.hongs.skycommon.pojo.entity
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com:
      hongs:
        skyserver:
          controller: info
          service: info
          mapper: debug

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: hongs
    # 设置jwt过期时间
    admin-ttl: 720000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

  alioss:
    access-key-id: ${hongs.alioss.access-key-id}
    access-key-secret: ${hongs.alioss.access-key-secret}
    endpoint: ${hongs.alioss.endpoint}
    bucket-name: ${hongs.alioss.bucket-name}
    region: ${hongs.alioss.region}