server:
  port: 8080

spring:
  application:
    name: sky-server
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: ${sky.datasource.driver-class-name}
    url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${sky.datasource.username}
    password: ${sky.datasource.password}

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.hongs.skycommon.pojo.entity
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com:
      hongs:
        skyserver:
          controller: info
          service: info
          mapper: debug

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: hongs
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token